final int SCREEN_X = 1920;
final int SCREEN_Y = 1080;
final int IMG_HEIGHT = 120;
final int IMG_WIDTH = 120;
final int STARTING_Y = 90;
final int EXPLOSION_INCREMENT = 6;
final int MARGIN = 60;
final int Y_MARGIN = 120;
final int PLAYER_X = 150;
final int PLAYER_Y = 120;
final int BULLET_X = 10;
final int BULLET_Y = 20;
final int NUM_OF_ALIENS = 20;
final int ALIEN_START_VEL = 2;
final int DEF_BULLET_SPEED = 8;
final int BULLET_LIMIT = 8;
final int POWERUP_RARITY = 15; //No lower than 3.